In [ ]:
import cv2 
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

1/1 [==============================] - 0s 317ms/step
[[0.20791559 0.23008193 0.50394225 0.05806023]]
1/1 [==============================] - 0s 14ms/step
[[0.22023962 0.23700395 0.48963094 0.05312552]]
1/1 [==============================] - 0s 14ms/step
[[0.21603079 0.23475136 0.4958818  0.05333599]]
1/1 [==============================] - 0s 13ms/step
[[0.22367878 0.23764959 0.4894016  0.04926995]]
1/1 [==============================] - 0s 26ms/step
[[0.21789457 0.2402321  0.49083778 0.05103554]]
1/1 [==============================] - 0s 13ms/step
[[0.21786153 0.23646088 0.4920471  0.05363043]]
1/1 [==============================] - 0s 13ms/step
[[0.2135996  0.24761254 0.4859518  0.05283609]]
1/1 [==============================] - 0s 13ms/step
[[0.198837   0.23301274 0.51346695 0.05468325]]
1/1 [==============================] - 0s 13ms/step
[[0.21070506 0.2432233  0.49391663 0.05215498]]
1/1 [==============================] - 0s 13ms/step
[[0.21072629 0.24237695 0.49712119 0.04977552]]

[[0.19334663 0.20780748 0.5522942  0.04655169]]
1/1 [==============================] - 0s 20ms/step
[[0.20140517 0.18863264 0.5593489  0.05061324]]
1/1 [==============================] - 0s 15ms/step
[[0.2025428  0.19288355 0.5545032  0.05007045]]
1/1 [==============================] - 0s 14ms/step
[[0.20909405 0.2065405  0.5367904  0.0475751 ]]
1/1 [==============================] - 0s 14ms/step
[[0.1976415  0.18962479 0.5651999  0.0475338 ]]
1/1 [==============================] - 0s 17ms/step
[[0.19701663 0.21581262 0.5346707  0.05250008]]
1/1 [==============================] - 0s 13ms/step
[[0.20685291 0.2013568  0.54244024 0.04935003]]
1/1 [==============================] - 0s 14ms/step
[[0.20351551 0.19810206 0.54720885 0.05117359]]
1/1 [==============================] - 0s 14ms/step
[[0.20029041 0.20594431 0.5456117  0.04815359]]
1/1 [==============================] - 0s 13ms/step
[[0.20881173 0.21760911 0.52778894 0.04579024]]
